# Generated by Django 2.0 on 2018-01-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
