# Generated by Django 2.0.2 on 2018-02-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180110_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Cart'),
            preserve_default=False,
        ),
    ]
